package generator;

import oppgaver.Oppgave4;

public class Oppgave4TestdataGenerator {

	private static final String NEW_LINE = "\n";

	public static void main(String[] args) {
		char[][][] ord = { 
							{	"QWERTY".toCharArray(), 
								"ASDFGF".toCharArray(), 
								"SSQQRS".toCharArray(), 
								"POIUWW".toCharArray() },
							{ 	"WSSSWS".toCharArray(), 
								"ASDSAW".toCharArray(), 
								"RSSSSA".toCharArray(), 
								"POIUAW".toCharArray(), 
								"SOIASW".toCharArray(), 
								"SOISSW".toCharArray() },
							{ 	"WFEWWS".toCharArray(), 
								"ASDSAW".toCharArray(), 
								"RSFESA".toCharArray(), 
								"SOIESW".toCharArray() },
							{ 	"WFEWW".toCharArray(), 
								"AHDFW".toCharArray(), 
								"AJDAW".toCharArray(), 
								"ATUAW".toCharArray(), 
								"RFEEA".toCharArray(), 
								"OIEWW".toCharArray() },
							{ 	"SSSSSS".toCharArray(), 
								"AHDFSW".toCharArray(), 
								"AJSUAW".toCharArray(), 
								"ATDUAW".toCharArray(), 
								"SSDUSW".toCharArray(), 
								"ASDUSW".toCharArray(), 
								"RSSESA".toCharArray(), 
								"OOIESW".toCharArray() },
							{ 	"SSSWWS".toCharArray(), 
								"AFDSAs".toCharArray(), 
								"SSFESS".toCharArray(), 
								"SOIEFW".toCharArray() },
							{ 	"SSSWWSSSSWSSSWWSSSSWSSSWWSSSSWSSSWWSSSS".toCharArray(), 
								"SWJFELFKJLEWASKLFKEWKJFLDSJFLEWKFWKLEWK".toCharArray(), 
								"ASLDJSALJFDOEWASLJFALWJASJFLAJFELQCLDMD".toCharArray(), 
								"SKDFKSJDNJKSHFWEFIUREGHKIJKFDKJESFLAKDS".toCharArray(), 
								"SDJVFKEWNJFISJNVKFHRGLIESJFLAJIEWHFKDKE".toCharArray(), 
								"DSKJDFNCLAKSJAØFKJOEJFAKSNFDKJGFNHALJEW".toCharArray(), 
								"ASLKJSSSSDJFLAFEJEFJKDKFSSLAJSFJIEWJFKL".toCharArray(), 
								"KLKKIJGRGFDIRHEHIEWAQHWHKJSDHAAKHFRLKAS".toCharArray(), 
								"LFKDSAKLJSDKJSSJFDLEJFKKKEJFJFWEFJWEKKF".toCharArray(), 
								"BBDSJFWESOJFELSSSHJEFLJSFLKJELJSEIJFLWE".toCharArray(), 
								"LKSDFSIESLKJGFJSLKJGLRHELOWJLRGLEKRGLRE".toCharArray(), 
								"LDSLJKSKJJKELSWELKKEJFWJFJEWIEIEIJFWIEW".toCharArray(), 
								"JJJREILGJLREJGLWIRELIFEWIREHFLFEILLFEWJ".toCharArray(), 
								"NVNVFLKRENJLKJFLKJFLDJFJRELFELLEWAALJEA".toCharArray(), 
								"AØLASJFLAJSSJLJFSLKJELFJEWLHGLREWLWAAKL".toCharArray(), 
								"NVXMDJFNCLSWJDFVJLKAJSKJDLAJAJAIWFSSKSF".toCharArray(), 
								"LKSDJFLWEJFLWEFJLKSDSAAAJFSSKSJFLWEKJSK".toCharArray(), 
								"MCBVKDRJLFJELSAKSLAJIFLEWAJFLJWEIGHJFDK".toCharArray(), 
								"SKDJFGLKREJLSKDSSKJEFLSEJIJSLKKSJISELJF".toCharArray(), 
								"MXNCKSEJFLSJLSAJSREFSKSSJFELJSLFEKJSEKW".toCharArray(), 
								"IEJFLKEWJKSAJFKSEJLKJFDSLJSJSKDJFSLKJLA".toCharArray(), 
								"SSSWWSSSSWSSSWWSSSSWSSSWWSSSSWSSSWWSSSS".toCharArray(),
								"LSKDJFLKJDFLJKSJLKSJLFEISFLKSSKJEFLISLK".toCharArray(), 
								"MXNCBVDJSKSAJFKRHGREKFLOEQØOWØAKLSDKJOE".toCharArray(), 
								"XNCBVKJDSALIJFLAEILRELFJØWQØPAØKDØLSAJF".toCharArray(), 
								"ÆØSLDFÅPWEØDSLFÆEPWEKFEWSWHJLKAEKEFHNWS".toCharArray(), 
								"VDSWNDCASNDSKJWAQLSJDKJDALSJDALKSJDJKSS".toCharArray(), 
								"CMNVKDJFNSNCDSLDFKJDLKCJLDSJFLFAØLOKFJO".toCharArray(), 
								"NCVSKLDAEWKFQLEIJWFLAKSKMXLSAEFJFHØLAWO".toCharArray(), 
								"NVKEWLNVMXSKHGOEPJEOIHFLAKSJFDLAKSJKKSK".toCharArray(), 
								"NNVNJKJDSNCMXMZMJSJZJNCNJJJKWFHHFHLIASS".toCharArray(), 
								"NCVMKERTYYELKKSLJFJFKJLSDSKJFJLJSLJRELE".toCharArray(), 
								"NCMJDJXMNCNCJDSJKKSAHJFHFHLSALKJFDSJSLA".toCharArray(), 
								"NBCMVXNDFSKDSLKLSJEFLJAJLASJSALJALKDSAØ".toCharArray(), 
								"XMCNVKSDNSKNDLWKEMCSLKMCKCSNMDKLNMCSWJF".toCharArray(), 
								"MXNCVKLDSAØPWQIFLKSAFDEKSCKNAKLSFJALKSD".toCharArray(), 
								"SMNDKCNLNSLSSKLDNFSLKENLWFKNSNLEWKLWSSN".toCharArray(), 
								"SSSWWSSSSWSSSWWSSSSWSSSWWSSSSWSSSWWSSSS".toCharArray(), 
								"MXCNVSDSLKNDVLKDSNDSNFDKELQJALASSLKJEFE".toCharArray() },
							{ 	"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS".toCharArray(), 
								"FWJFELFKJLEWAFKLFKEWKJFLDFJFLEWKFWKLEWS".toCharArray(), 
								"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSMS".toCharArray(), 
								"SKDFKFJDNJKFHFWEFIUREGHKIJKFDKJEFFLASDS".toCharArray(), 
								"SDSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSKSKS".toCharArray(), 
								"SFSJDFNCLAKFJAØFKJOEJFAKFNFDKJGFNHSLSES".toCharArray(), 
								"SFSKSSSSSSSSSSSSSSSSSSSSSSSSSSSSSESJSKS".toCharArray(), 
								"SLSKSJGRGFDIRHEHIEWAQHWHKJFDHAAKSFSLSAS".toCharArray(), 
								"SFSDSASSSSSSSSSSSSSSSSSSSSSSSSWESJSESKS".toCharArray(), 
								"SBSFSFSEFOJFELFFFHJEFLJFFLKJESJFSISFSWS".toCharArray(), 
								"SKSDSFSESSSSSSSSSSSSSSSSSSSSLSGLSKSGSRS".toCharArray(), 
								"SDSLSKSKSJKELFWELKKEJFWJFJESISIESJSWSES".toCharArray(), 
								"SJSRSISGSLSSSSSSSSSSSSSSSSESFSFESLSFSWS".toCharArray(), 
								"SVSVSLSRSNSLKJFLKJFLDJFJRSLSESLESASLSES".toCharArray(), 
								"SØSASJSLSJSFSSSSSSSSSSSSESLSGSRESLSASKS".toCharArray(), 
								"SVSMSJSNSLSWSDFVJLKAJFKSDSASASAISFSFSFS".toCharArray(), 
								"SKSDSFSWSJSLSESSSSSSSSASJSFSKSJFSWSKSFS".toCharArray(), 
								"SCSVSDSJSFSESFSKFLAJISLSWSJSLSWESGSJSDS".toCharArray(), 
								"SKSJSGSKSESLSKSFSSSSFSFSJSJSLSKFSISESJS".toCharArray(), 
								"SXSCSFSJSLSJSFSJSRESFSFSJSESJSLFSKSFSKS".toCharArray(), 
								"SESFSKSWSKSASFSFSJSSJSDSLSFSFSDJSFSKSLS".toCharArray(), 
								"SFSWSFSFSWSFSWSFSFFWFSFSWSFSFSFFSWSFSFS".toCharArray(),
								"SFSDSFSKSDSLSKSJSSSSSSESFSLSFSKJSFSISLS".toCharArray(), 
								"SXSCSVSJSKSASFSRHGREKFLSESØSWSAKSFSKSOS".toCharArray(), 
								"SNSBSKSDSASISFSSSSSSSSSSØSQSPSØKSØSFSJS".toCharArray(), 
								"SØSLSFSPSESDSLFÆEPWEKFEWFSHSLSAESESHSWS".toCharArray(), 
								"SDSWSDSASNSFSSSSSSSSSSSSSSFSDSLKSJSJSFS".toCharArray(), 
								"SMSVSDSFSFSCDFLDFKJDLKCJLDFSFSFASLSKSJS".toCharArray(), 
								"SCSFSLSASWSSSSSSSSSSSSSSSSSSASFJSHSLSWS".toCharArray(), 
								"SVSESLSVSXFKHGOEPJEOIHFLAKFJFSLASFSKSFS".toCharArray(), 
								"SNSNSKSDSSSSSSSSSSSSSSSSSSSSSSHHSHSISFS".toCharArray(), 
								"SCSMSESTYYELKKFLJFJFKJLFDFKJFJLJSLSRSLS".toCharArray(), 
								"SCSJSJSSSSSSSSSSSSSSSSSSSSSSSSSSSDSJSLS".toCharArray(), 
								"SBSMSXNDFFKDFLKLFJEFLJAJLAFJFALJALSDSAS".toCharArray(), 
								"SMSNSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSFSJS".toCharArray(), 
								"SXSCVKLDFAØPWQIFLKFAFDEKFCKNAKLFFJALSFS".toCharArray(), 
								"SMSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSFS".toCharArray(), 
								"SFFWWFFFFWFFFWWFFFFWFFFWWFFFFWFFFWWFFFS".toCharArray(), 
								"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS".toCharArray() },
							{ 	"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS".toCharArray(), 
								"FWJFELFKJLEWAFKLFKEWKJFLDFJFLEWKFWKLEWS".toCharArray(), 
								"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSMS".toCharArray(), 
								"SKDFKFJDNJKFHFWEFIUREGHKIJKFDKJEFFLASDS".toCharArray(), 
								"SDSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSKSKS".toCharArray(), 
								"SFSJDFNCLAKFJAØFKJOEJFAKFNFDKJGFNHSLSES".toCharArray(), 
								"SFSKSSSSSSSSSSSSSSSSSSSSSSSSSSSSSESJSKS".toCharArray(), 
								"SLSKSJGRGFDIRHEHIEWAQHWHKJFDHAAKSFSLSAS".toCharArray(), 
								"SFSDSASSSSSSSSSSSSSSSSSSSSSSSSWESJSESKS".toCharArray(), 
								"SBSFSFSEFOJFELFFFHJEFLJFFLKJESJFSISFSWS".toCharArray(), 
								"SKSDSFSESSSSSSSSSSSSSSSSSSSSLSGLSKSGSRS".toCharArray(), 
								"SDSLSKSKSJKELFWELKKEJFWJFJESISIESJSWSES".toCharArray(), 
								"SJSRSISGSLSSSSSSSSSSSSSSSSESFSFESLSFSWS".toCharArray(), 
								"SVSVSLSRSNSLKJFLKJFLDJFJRSLSESLESASLSES".toCharArray(), 
								"SØSASJSLSJSFSSSSSSSSSSSSESLSGSRESLSASKS".toCharArray(), 
								"SVSMSJSNSLSWSDFVJLKAJFKSDSASASAISFSFSFS".toCharArray(), 
								"SKSDSFSWSJSLSESSSSSSSSASJSFSKSJFSWSKSFS".toCharArray(), 
								"SCSVSDSJSFSESFSKFLAJISLSWSJSLSWESGSJSDS".toCharArray(), 
								"SKSJSGSKSESLSKSFSSSSFSFSJSJSLSKFSISESJS".toCharArray(), 
								"SXSCSFSJSLSJSFSJSRESFSFSJSESJSLFSKSFSKS".toCharArray(), 
								"SESFSKSWSKSASFSFSJSSJSDSLSFSFSDJSFSKSLS".toCharArray(), 
								"SFSWSFSFSWSFSWSFSFFWFSFSWSFSFSFFSWSFSFS".toCharArray(),
								"SFSDSFSKSDSLSKSJSSSSSSESFSLSFSKJSFSISLS".toCharArray(), 
								"SXSCSVSJSKSASFSRHGREKFLSESØSWSAKSFSKSOS".toCharArray(), 
								"SNSBSKSDSASISFSSSSSSSSSSØSQSPSØKSØSFSJS".toCharArray(), 
								"SØSLSFSPSESDSLFÆEPWEKFEWFSHSLSAESESHSWS".toCharArray(), 
								"SDSWSDSASNSFSSSSSSSSSSSSSSFSDSLKSJSJSFS".toCharArray(), 
								"SMSVSDSFSFSCDFLDFKJDLKCJLDFSFSFASLSKSJS".toCharArray(), 
								"SCSFSLSASWSSSSSSSSSSSSSSSSSSASFJSHSLSWS".toCharArray(), 
								"SVSESLSVSXFKHGOEPJEOIHFLAKFJFSLASFSKSFS".toCharArray(), 
								"SNSNSKSDSSSSSSSSSSSSSSSSSSSSSSHHSHSISFS".toCharArray(), 
								"SCSMSESTYYELKKFLJFJFKJLFDFKJFJLJSLSRSLS".toCharArray(), 
								"SCSJSJSSSSSSSSSSSSSSSSSSSSSSSSSSSDSJSLS".toCharArray(), 
								"SBSMSXNDFFKDFLKLFJEFLJAJLAFJFALJALSDSAS".toCharArray(), 
								"SMSNSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSFSJS".toCharArray(), 
								"SXSCVKLDFAØPWQIFLKFAFDEKFCKNAKLFFJALSFS".toCharArray(), 
								"SMSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSFS".toCharArray(), 
								"SFFWWFFFFWFFFWWFFFFWFFFWWFFFFWFFFWWFFFS".toCharArray(), 
								"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS".toCharArray() },
							{ 	"SSSS".toCharArray(), 
								"SSSS".toCharArray(), 
								"SSSS".toCharArray() }};
		System.out.println(genererInputFil(ord));
		System.out.println("----------------------");
		System.out.println(genererOutputFil(ord));
	}

	private static String genererOutputFil(char[][][] ord) {
		Oppgave4 opg = new Oppgave4();
		StringBuilder builder = new StringBuilder();
		for (char[][] p : ord) {
			builder.append(opg.tellFlokker(p)).append(NEW_LINE);
		}

		return builder.toString();
	}

	private static String genererInputFil(char[][][] ord) {
		StringBuilder builder = new StringBuilder();
		builder.append(ord.length).append(NEW_LINE);
		for (char[][] string : ord) {
			builder.append(string.length).append(" ").append(string[0].length).append(NEW_LINE);
			for (char[] cs : string) {
				for (char c : cs) {
					builder.append(c);
				}
				builder.append(NEW_LINE);
			}
		}

		return builder.toString();
	}

	// 2 1
	// 4 6 2
	// QWERTY
	// ASDFGS
	// SSQQRS
	// POIUWW
	// 6 6
	// WSSSWS
	// ASDSAW
	// RSSSSA
	// POIUAW
	// SOIASW
	// SOISSW
}
